services:
  # 1. Banco de dados do seu projeto de dados
  postgres_lab:
    image: postgres:15-alpine
    container_name: postgres_lab
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: engenharia_dados
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Servidor standalone do Apache Airflow
  airflow:
    image: apache/airflow:2.8.1-python3.10
    container_name: airflow_standalone
    depends_on:
      - postgres_lab
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: standalone

volumes:
  pgdata: